name: biobb_wf_mem
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_mem==5.2.1
  - biobb_io==5.2.2
  - biobb_analysis==5.2.0
  - anywidget
  - plotly
  - nglview
  - jupyterlab=3.6
  - nodejs=16
  - ipywidgets=7
